define([
  './dash',
  './dashLoader',
  './influxLoginCtrl',
  './row',
  './submenuCtrl',
  './pulldown',
  './search',
  './metricKeys',
  './graphiteTarget',
  './graphiteImport',
  './influxTargetCtrl',
  './playlistCtrl',
  './inspectCtrl',
], function () {});
